#!/bin/bash
#SBATCH --job-name=21-FIO
#SBATCH --partition x20core
#SBATCH --nodes=1 --ntasks-per-node=40
#SBATCH --time=30:00
#SBATCH --chdir=.

filename=re-mvm-1152-mpi.dat

export OMP_NUM_THREADS=1
rm -f $filename
for p in 1 2 3 4 6 8 9 12 16 18 24 32 36 ; do
    mpirun -np $p ./mvm1152 >> $filename
done
