#!/bin/bash
#SBATCH --job-name=21-FIO
#SBATCH --partition x20core
#SBATCH --nodes=1 --ntasks-per-node=40
#SBATCH --time=30:00
#SBATCH --chdir=.

filename=re-mvm-1152-omp.dat

rm -f $filename
for p in 1 2 3 4 6 8 9 12 16 18 24 32 36 ; do
  export OMP_NUM_THREADS=$p ; mpirun -np 1 ./mvm1152 >> $filename ;
done
